CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS film_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    price DOUBLE DEFAULT 0.0,
    available_content INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATETIME,
    payment_date DATETIME,
    remaining_content INT,
    film_category_id BIGINT,
    FOREIGN KEY (film_category_id) REFERENCES film_category(id)
);

CREATE TABLE IF NOT EXISTS customer_subscription (
    customer_id BIGINT,
    subscription_id BIGINT,
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id),
    PRIMARY KEY (customer_id, subscription_id)
);